# Naunet config document

[general]
creation_time = "30/08/2022 16:09:07"
name = "naunet_klu_deuterium"
description = "Example: deuterium network used in Hsu et al. 2021"
loads = []

[chemistry]
elements = ["e", "H", "D", "He", "C", "N", "O", "GRAIN"]
pseudo_elements = ["o", "p", "m"]
species = ["C", "C+", "C-", "C2", "C2+", "C2D", "C2D+", "C2H", "C2H+", "C2N", "C2N+", "C2O+", "C3", "C3+", "CCO", "CD", "CD+", "CD2", "CD2+", "CH", "CH+", "CH2", "CH2+", "CHD", "CHD+", "CN", "CN+", "CN-", "CNC+", "CO", "CO+", "CO2", "CO2+", "D", "D+", "D-", "D2O", "D2O+", "D3O+", "DCN", "DCN+", "DCO", "DCO+", "DNC", "DNC+", "DNO", "DNO+", "DOC+", "GRAIN-", "GRAIN0", "H", "H+", "H-", "H2DO+", "H2O", "H2O+", "H3O+", "HCN", "HCN+", "HCO", "HCO+", "HD", "HD+", "HD2O+", "HDO", "HDO+", "HNC", "HNC+", "HNO", "HNO+", "HOC+", "He", "He+", "HeD+", "HeH+", "N", "N+", "N2", "N2+", "N2D+", "N2H+", "N2O", "NCO+", "ND", "ND+", "ND2", "ND2+", "NH", "NH+", "NH2", "NH2+", "NHD", "NHD+", "NO", "NO+", "NO2", "NO2+", "O", "O+", "O-", "O2", "O2+", "O2D", "O2D+", "O2H", "O2H+", "OCN", "OD", "OD+", "OD-", "OH", "OH+", "OH-", "e-", "mD3+", "oD2", "oD2+", "oD2H+", "oD3+", "oH2", "oH2+", "oH2D+", "oH3+", "pD2", "pD2+", "pD2H+", "pD3+", "pH2", "pH2+", "pH2D+", "pH3+"]
extra_species = []
network = ["deuterium.krome"]
format = ["krome"]
heating = []
cooling = []
ode_modifier = []

[chemistry.grain]
model = ""

[chemistry.binding_energy]

[chemistry.photon_yield]

[chemistry.shielding]

[chemistry.rate_modifier]

[ODEsolver]
solver = "cvode"
device = "cpu"
method = "sparse"

[summary]
num_of_species = 131
num_of_grains = 0
num_of_gas_species = 131
num_of_ice_species = 0
num_of_grain_species = 0
num_of_reactions = 3466
list_of_species = ["C2O+", "NCO+", "O2D", "O2H", "C2N", "CCO", "CNC+", "N2O", "C3", "HeH+", "C3+", "HeD+", "OCN", "DNC", "HNC", "HOC+", "DOC+", "OD-", "OH-", "CN-", "NO2+", "NO2", "DNO", "HNO", "C2N+", "GRAIN-", "GRAIN0", "DNC+", "HNC+", "O-", "CO2+", "C-", "O2H+", "O2D+", "N2H+", "N2D+", "HNO+", "DNO+", "C2D", "C2H", "H3O+", "pD3+", "D3O+", "H-", "CO2", "mD3+", "oD3+", "D-", "oH3+", "pH3+", "DCN", "HCN", "CD2", "CH2", "HCN+", "ND2", "NH2", "DCN+", "C2+", "C2H+", "C2D+", "CHD", "CH2+", "NHD", "CD2+", "H2DO+", "HD2O+", "NH+", "NH2+", "C+", "N+", "N2+", "ND+", "ND2+", "O2+", "CO+", "CN+", "He+", "NHD+", "O+", "OH+", "OD+", "CHD+", "HCO", "oH2+", "DCO", "oD2H+", "oH2D+", "pD2H+", "pH2D+", "pH2+", "H2O+", "HCO+", "D2O+", "DCO+", "oD2+", "pD2+", "CH+", "He", "CD+", "HDO+", "H+", "NO+", "D+", "HD+", "NH", "N2", "ND", "C2", "CH", "CD", "O2", "D2O", "H2O", "NO", "HDO", "OH", "oD2", "oH2", "CN", "OD", "C", "CO", "N", "O", "pD2", "pH2", "HD", "e-", "D", "H"]
list_of_species_alias = ["C2OII", "NCOII", "O2DI", "O2HI", "C2NI", "CCOI", "CNCII", "N2OI", "C3I", "HeHII", "C3II", "HeDII", "OCNI", "DNCI", "HNCI", "HOCII", "DOCII", "ODM", "OHM", "CNM", "NO2II", "NO2I", "DNOI", "HNOI", "C2NII", "GRAINM", "GRAIN0I", "DNCII", "HNCII", "OM", "CO2II", "CM", "O2HII", "O2DII", "N2HII", "N2DII", "HNOII", "DNOII", "C2DI", "C2HI", "H3OII", "pD3II", "D3OII", "HM", "CO2I", "mD3II", "oD3II", "DM", "oH3II", "pH3II", "DCNI", "HCNI", "CD2I", "CH2I", "HCNII", "ND2I", "NH2I", "DCNII", "C2II", "C2HII", "C2DII", "CHDI", "CH2II", "NHDI", "CD2II", "H2DOII", "HD2OII", "NHII", "NH2II", "CII", "NII", "N2II", "NDII", "ND2II", "O2II", "COII", "CNII", "HeII", "NHDII", "OII", "OHII", "ODII", "CHDII", "HCOI", "oH2II", "DCOI", "oD2HII", "oH2DII", "pD2HII", "pH2DII", "pH2II", "H2OII", "HCOII", "D2OII", "DCOII", "oD2II", "pD2II", "CHII", "HeI", "CDII", "HDOII", "HII", "NOII", "DII", "HDII", "NHI", "N2I", "NDI", "C2I", "CHI", "CDI", "O2I", "D2OI", "H2OI", "NOI", "HDOI", "OHI", "oD2I", "oH2I", "CNI", "ODI", "CI", "COI", "NI", "OI", "pD2I", "pH2I", "HDI", "eM", "DI", "HI"]
list_of_gas_species = ["C2O+", "NCO+", "O2D", "O2H", "C2N", "CCO", "CNC+", "N2O", "C3", "HeH+", "C3+", "HeD+", "OCN", "DNC", "HNC", "HOC+", "DOC+", "OD-", "OH-", "CN-", "NO2+", "NO2", "DNO", "HNO", "C2N+", "GRAIN-", "GRAIN0", "DNC+", "HNC+", "O-", "CO2+", "C-", "O2H+", "O2D+", "N2H+", "N2D+", "HNO+", "DNO+", "C2D", "C2H", "H3O+", "pD3+", "D3O+", "H-", "CO2", "mD3+", "oD3+", "D-", "oH3+", "pH3+", "DCN", "HCN", "CD2", "CH2", "HCN+", "ND2", "NH2", "DCN+", "C2+", "C2H+", "C2D+", "CHD", "CH2+", "NHD", "CD2+", "H2DO+", "HD2O+", "NH+", "NH2+", "C+", "N+", "N2+", "ND+", "ND2+", "O2+", "CO+", "CN+", "He+", "NHD+", "O+", "OH+", "OD+", "CHD+", "HCO", "oH2+", "DCO", "oD2H+", "oH2D+", "pD2H+", "pH2D+", "pH2+", "H2O+", "HCO+", "D2O+", "DCO+", "oD2+", "pD2+", "CH+", "He", "CD+", "HDO+", "H+", "NO+", "D+", "HD+", "NH", "N2", "ND", "C2", "CH", "CD", "O2", "D2O", "H2O", "NO", "HDO", "OH", "oD2", "oH2", "CN", "OD", "C", "CO", "N", "O", "pD2", "pH2", "HD", "e-", "D", "H"]
list_of_ice_species = []
list_of_grain_species = []

